### PR TITLE
Feature/issue 95 fix multiple faces slowness

### PR DESCRIPTION
**Pull request by Dutch77**
Issue #95

What I did:

- added method `analyse_image` and calling it only when needed
- added parameter `image_analysis` to `get_face_single` method so we can pass calculated analysis
- removed method `reget_face_single` and replaced it with `get_face_single` which is called on those places with halfed `det_size`

### CODE REVIEW

**Comment by Gourieff** [comment]
I've made a test today
This is the result

Win10 RTX 3060, 768x960 DPM++ 2M Karras 15 steps
ReActor has default settings

<table style="display:inline-block">
  <tr>
    <th>
      Without Patch
    </th>
    <th>
      A1111 1.6.0
    </th>
    <th>
      A1111 1.5.2
    </th>
  </tr>
  <tr>
    <td>
      1st run
    </td>
    <td>
      25.0
    </td>
    <td>
      23.9
    </td>
  </tr>
  <tr>
    <td>
      2nd run
    </td>
    <td>
      19.7
    </td>
    <td>
      18.3
    </td>
  </tr>
  <tr>
    <td>
      3rd run
    </td>
    <td>
      19.9
    </td>
    <td>
      18.6
    </td>
  </tr>
  <tr>
    <td>
      4th run
    </td>
    <td>
      19.4
    </td>
    <td>
      18.5
    </td>
  </tr>
  <tr>
    <td>
      5th run
    </td>
    <td>
      19.3
    </td>
    <td>
      18.3
    </td>
  </tr>
  <tr>
    <td>
      6th run
    </td>
    <td>
      18.4
    </td>
    <td>
      18.3
    </td>
  </tr>
  <tr>
    <td>
      <b>Average (2-6)</b>
    </td>
    <td>
      <b>19.34</b>
    </td>
    <td>
      <b>18.4</b>
    </td>
  </tr>
</table>

<table>
  <tr>
    <th>
      With your Patch
    </th>
    <th>
      A1111 1.6.0
    </th>
    <th>
      A1111 1.5.2
    </th>
  </tr>
  <tr>
    <td>
      1st run
    </td>
    <td>
      24.9
    </td>
    <td>
      23.6
    </td>
  </tr>
  <tr>
    <td>
      2nd run
    </td>
    <td>
      20.4
    </td>
    <td>
      18.9
    </td>
  </tr>
  <tr>
    <td>
      3rd run
    </td>
    <td>
      20.2
    </td>
    <td>
      18.5
    </td>
  </tr>
  <tr>
    <td>
      4th run
    </td>
    <td>
      19.0
    </td>
    <td>
      18.4
    </td>
  </tr>
  <tr>
    <td>
      5th run
    </td>
    <td>
      18.2
    </td>
    <td>
      19.0
    </td>
  </tr>
  <tr>
    <td>
      6th run
    </td>
    <td>
      19.2
    </td>
    <td>
      19.1
    </td>
  </tr>
  <tr>
    <td>
      <b>Average (2-6)</b>
    </td>
    <td>
      <b>19.4</b>
    </td>
    <td>
      <b>18.78</b>
    </td>
  </tr>
</table>

So, there's no difference at all, even quite a little slower on average

**Comment by Dutch77** [comment]
Are you swapping single face? Because that **was never the issue**... Check #95 what you and me wrote there. Try swapping 10 people faces with another 10 people and you will see the difference.

Point of this PR is **not doing face analysis with each face** because this operation costs **~1s** on AMD Ryzen 5600 with 3060GTX. So 10 people = unnecessary ~10s

**Comment by Dutch77** [comment]
Or just set this and see how slow it can be if those faces are not there
```
"source_faces_index": [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29],
"face_index": [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29]
```

**Comment by Dutch77** [comment]
I've generated this image

My PC - Intel i7 1065g + nvidia 1080gtx

API call:
POST `/reactor/image`
```
{
  "source_image": "base64 of image above",
  "target_image": "base64 of image above"
  "source_faces_index": [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29],
  "face_index": [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29]
}
```

Main branch:
`70.14s`, `82.02s`, `81.56s`

My branch
`12.68s`, `8.06s`, `10.07s`

On this extreme case I was able to be faster by a minute. Please do your speeds test again :(

**Comment by Gourieff** [comment]
Sorry for my inattention 🤔 I will retest this week

**Comment by Gourieff** [comment]
Confirmed! Really much faster with multiple faces 👍🏻
Could you sync your changes with the latest commits and make a new PR to the "evolve" branch?

**Comment by Dutch77** [comment]
@Gourieff I guess no need to create new PR, I have just rebased the branch up to your main branch.

**Comment by Gourieff** [comment]
Tested again, everything is ok with how it fast
But I noticed that a gender logging (when detecting a face) is broken in your version, it shows "None" every time
изображение

And that's how it is in the Main branch:
изображение

And also there's no need to send "img_data" into the "get_face_single" function when using the separate analyzing function
And there's no need in the separate half_det function
And the best way to call faces analyzer in this case is to do it in the very beginning 

So, I want to implement this with all the corrections and fixes and with a little different logic in some moments
And to keep things fair I'll add you as a Contributor for the commit and also as a Contributor for the 0.4.2 Release

**Pull request closed without merging**
