### PR TITLE
Add Masking option

### PR DESCRIPTION
**Pull request by jiveabillion**
This adds a checkbox under the "Save Original" check box to configure the extension to detect face areas on the original image and create a mask that will be applied to the swapped image and merged to create the final image so that it will be more precise than a rectangle and avoid blurring of details surrounding faces caused by inswapper and codeformer.

### CODE REVIEW

**Comment by Gourieff** [comment]
Great! 👍🏻 I will test it this week

**Comment by Gourieff** [comment]
Unfortunately it ruins the final result
It seems that facerestoration doesn't work (or works in inverted way) when "Mask Faces" is On

---
Original:
00000-0riginal

---
Swapped with **Mask Faces OFF** and CodeFormer ON
00000-408658206--NoMASK+CodeFormer

---
Swapped with **Mask Faces ON** and CodeFormer ON
00001-408658206--MASK+CodeFormer

---
Swapped with **Mask Faces ON** and GFPGAN ON
00002-408658206--MASK+GFPGAN

---
Swapped with **Mask Faces OFF** and Face Restoration OFF
00003-408658206--NoMASK--NoFaceRestoration

---
Swapped with **Mask Faces ON** and Face Restoration OFF
00004-408658206--MASK--NoFaceRestoration

**Comment by jiveabillion** [comment]
hmm, it must be the order it's doing it in or something. I'll check

**Comment by jiveabillion** [comment]
nope, it's actually simpler than that. ill have another PR here in a few

**Comment by jiveabillion** [comment]
that should do it

**Comment by Gourieff** [comment]
Yes, works great now 👍🏻

изображение

Thanks for this PR!
I will prepare Evolve branch and merge it there and then after some cosmetics I will merge it into Main

**Comment by jiveabillion** [comment]
Sounds good to me 👍🏻

**Pull request merged**
